apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kashif-website-ingress
  namespace: kashif-portfolio
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: kashif.duperbots.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kashif-website-service
            port:
              number: 80